### ISSUE TITLE
Github labels overlap while extension is activated

### ISSUE THREAD

**Issue by arnlaugsson** [koddsson/github-emojis#5]
When extension activated, labels in Github issues start overlapping, on both a single issue and an issue list.

By disabling the extension and reloading the labels were arranged correctly.

**With extension**
![screen shot 2014-12-10 at 09 34 11](https://cloud.githubusercontent.com/assets/206842/5373622/d3e4e38a-804f-11e4-9f2d-e7bd62bbec67.png)

**Without extension**
![screen shot 2014-12-10 at 09 33 39](https://cloud.githubusercontent.com/assets/206842/5373626/db5009a6-804f-11e4-9218-4987ad8de3b8.png)

**Comment by Ikornaselur** [comment]
So thaaat's the reason for the labels overlapping. I noticed yesterday when opening github for the first time in ~2 weeks that it was fixed. It made me so happy.

**Comment by Ikornaselur** [comment]
Btw, should this still be open?

**Comment by koddsson** [comment]
nah, thanks for the reminder :)
